Config = {}
Config.ESX = true
Config.BotToken = ""
Config.WebHook = ""
Config.ChannelID = ""
Config.ReplyUserName = "Prison RP | Commande IG"
Config.AvatarURL = ""
Config.Prefix = "+"
Config.WaitEveryTick = 4000  -- ITS MS
