print("^2 ================================================================ ")
print("")
print("")
print("^1\t\t   JOKER CORE")
print("^3\t      Tout est charger sans erreur!")
print("")
print("\t\t^1Crée par 𝐉𝐎𝐊𝐄𝐑#0001")
print("")
print("^2 ================================================================")